import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { renderAgentsMd, renderCursorRules } from "@your-os/agent-context";
import type { TenantConfig } from "@your-os/tenant-config";

export interface InitTenantOptions {
  tenant: TenantConfig;
  /** Where to scaffold. */
  outDir: string;
  /** Optional preface for AGENTS.md. */
  preface?: string;
  /** Skip writing files; return what would be written. Used in tests. */
  dryRun?: boolean;
}

export interface InitTenantResult {
  files: Array<{ path: string; contents: string }>;
}

/**
 * Scaffolds a tenant repo from a tenant config. Phase 2 emits the canonical
 * skeleton; the configurator (Phase 3+) wraps this and adds GitHub OAuth +
 * optional Strapi provisioning.
 *
 * Files written:
 *   - tenant.config.ts       (importable by the tenant's app + by @your-os/cli sync)
 *   - AGENTS.md              (for Cursor/Claude/Codex)
 *   - .cursor/rules/*.mdc    (per-tenant rules)
 *   - README.md              (tenant intro)
 *   - package.json           (declares @your-os/* peer deps)
 *   - src/content/.gitkeep   (where TS data files go for code-mode tenants)
 */
export async function initTenant(opts: InitTenantOptions): Promise<InitTenantResult> {
  const files: Array<{ path: string; contents: string }> = [];

  files.push({
    path: "tenant.config.ts",
    contents: renderTenantConfigTs(opts.tenant),
  });

  files.push({
    path: "AGENTS.md",
    contents: renderAgentsMd({ tenant: opts.tenant, preface: opts.preface }),
  });

  for (const rule of renderCursorRules({ tenant: opts.tenant })) {
    files.push(rule);
  }

  files.push({
    path: "README.md",
    contents: renderReadme(opts.tenant),
  });

  files.push({
    path: "package.json",
    contents: renderPackageJson(opts.tenant),
  });

  files.push({
    path: "src/content/.gitkeep",
    contents: "",
  });

  if (!opts.dryRun) {
    for (const file of files) {
      const full = join(opts.outDir, file.path);
      await mkdir(join(full, ".."), { recursive: true });
      await writeFile(full, file.contents, "utf-8");
    }
  }

  return { files };
}

function renderTenantConfigTs(tenant: TenantConfig): string {
  return `import { defineTenant } from "@your-os/tenant-config";

export const tenantConfig = defineTenant(${JSON.stringify(tenant, null, 2)});

export default tenantConfig;
`;
}

function renderReadme(tenant: TenantConfig): string {
  return `# ${tenant.identity.name}

> Generated by \`@your-os/cli init\`.

This tenant repo consumes \`@your-os/*\` packages. To make changes:

1. Edit \`tenant.config.ts\`.
2. Run \`pnpm exec your-os sync\` to regenerate \`AGENTS.md\` + \`.cursor/rules/*\`.
3. Add content under \`src/content/<type>/<slug>.ts\` (code-mode) or via your Strapi admin (Strapi-mode).

## Brand-lint

\`\`\`bash
pnpm exec your-os-brand-lint --staged
\`\`\`
`;
}

function renderPackageJson(tenant: TenantConfig): string {
  const pkg = {
    name: tenant.identity.slug,
    version: "0.0.0",
    private: true,
    type: "module",
    scripts: {
      "brand:lint": "your-os-brand-lint --all",
      "your-os": "your-os",
    },
    dependencies: {
      "@your-os/brand-lint": "^0.0.0",
      "@your-os/cli": "^0.0.0",
      "@your-os/content-source": "^0.0.0",
      "@your-os/seo": "^0.0.0",
      "@your-os/tenant-config": "^0.0.0",
    },
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}
