import type { DeployOptions } from "../generator.js";

export function renderEnvExample(opts: DeployOptions): string {
  return `# Generated by @your-os/strapi-deploy. Copy to .env and fill secrets.
# Tenant: ${opts.tenantSlug}

HOST=0.0.0.0
PORT=1337

# Per-tenant: never share with other tenants
APP_KEYS=
API_TOKEN_SALT=
ADMIN_JWT_SECRET=
TRANSFER_TOKEN_SALT=
JWT_SECRET=

# Postgres (managed by provider)
DATABASE_CLIENT=postgres
DATABASE_URL=

# Media (S3-compatible)
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=us-east-1
AWS_BUCKET=${opts.tenantSlug}-strapi-media

# OS integration: locked down in production
STRAPI_ADMIN_DISABLE_CONTENT_TYPE_BUILDER=true

# Webhook → Next.js ISR
STRAPI_WEBHOOK_SECRET=
STRAPI_DRAFT_SECRET=
NEXT_REVALIDATE_URL=https://${opts.hostname.replace(/^cms\./, "")}/api/revalidate

# Brand-lint hook (validates editorial content before publish)
STRAPI_BRAND_LINT_API=  # internal API URL hosting @your-os/brand-lint
`;
}
