import type { DeployOptions } from "../generator.js";

export function renderFlyToml(opts: DeployOptions): string {
  return `# Generated by @your-os/strapi-deploy.
app = "${opts.tenantSlug}-strapi"
primary_region = "${opts.region ?? "iad"}"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  STRAPI_ADMIN_DISABLE_CONTENT_TYPE_BUILDER = "true"
  HOST = "0.0.0.0"
  PORT = "1337"

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/_health"

[mounts]
  source = "${opts.tenantSlug}_strapi_data"
  destination = "/app/data"

[[services]]
  protocol = "tcp"
  internal_port = 1337
`;
}
