import type { DeployOptions } from "../generator.js";

export function renderRenderBlueprint(opts: DeployOptions): string {
  return `# Generated by @your-os/strapi-deploy.
# Tenant: ${opts.tenantSlug}
services:
  - type: web
    name: ${opts.tenantSlug}-strapi
    runtime: docker
    plan: starter
    region: ${opts.region ?? "oregon"}
    healthCheckPath: /_health
    autoDeploy: true
    domains:
      - ${opts.hostname}
    envVars:
      - key: NODE_ENV
        value: production
      - key: STRAPI_ADMIN_DISABLE_CONTENT_TYPE_BUILDER
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: ${opts.tenantSlug}-strapi-db
          property: connectionString
databases:
  - name: ${opts.tenantSlug}-strapi-db
    plan: basic-256mb
    databaseName: ${opts.tenantSlug.replace(/-/g, "_")}_strapi
    user: ${opts.tenantSlug.replace(/-/g, "_")}_strapi
`;
}
