import type { DeployOptions, DeployProvider } from "../generator.js";

export function renderRunbook(provider: DeployProvider, opts: DeployOptions): string {
  return `# ${opts.tenantSlug} Strapi runbook (${provider})

> Generated by @your-os/strapi-deploy.

## Hostname

\`https://${opts.hostname}\`

## First-time provisioning

1. Provision Postgres + S3 bucket via the provider's UI/CLI.
2. Set every variable from \`.env.example\` as a provider secret. The
   per-tenant ones (APP_KEYS, JWT_SECRET, etc.) MUST be unique to this
   tenant — never reuse across tenants.
3. Apply the provider config (\`render.yaml\` / \`railway.json\` / \`fly.toml\`).
4. Wait for first deploy to go green.
5. Run schema migration: \`pnpm exec your-os strapi:migrate --tenant ${opts.tenantSlug}\`.

## Backups

- Postgres: nightly snapshot via the provider's managed backup service.
- Media (S3): bucket-level versioning enabled in \`.env.example\`.
- Test restore quarterly. Document RTO + RPO in this file.

## Webhooks

- Strapi → Next.js \`POST ${opts.hostname.replace(/^cms\./, "")}/api/revalidate\`.
- HMAC signed via \`STRAPI_WEBHOOK_SECRET\`.
- Latency target ≤ 60s p95 from \`entry.publish\` to live page.
- If publish does not appear in 90s: see @your-os/strapi-sync runbook section.

## Brand-lint

The \`@your-os/strapi-brand-lint-hook\` is wired in as a \`beforePublish\`
lifecycle. If editors hit a publish error mentioning a banned phrase or
missing citation, that is the hook firing — they must address inline.

## Schema changes

NEVER edit content-types via the admin UI in production
(\`STRAPI_ADMIN_DISABLE_CONTENT_TYPE_BUILDER=true\`). Schema changes ship
via \`@your-os/strapi-template\` major bumps + a migration runner step.
`;
}
