import { listSkills } from "@your-os/skills";
import type { TenantConfig } from "@your-os/tenant-config";

export interface RenderAgentsMdOptions {
  tenant: TenantConfig;
  /** Optional preface (e.g. tenant-team-specific lore). */
  preface?: string;
  /** Skip the skills index. Useful for very small tenants. */
  omitSkills?: boolean;
}

/**
 * Produces a tenant's `AGENTS.md`. Read by Cursor / Claude Code / any
 * coding agent on every session.
 */
export function renderAgentsMd(opts: RenderAgentsMdOptions): string {
  const { tenant, preface, omitSkills } = opts;
  const hasStrapi = Boolean(tenant.strapi);
  const skills = omitSkills
    ? []
    : listSkills({ businessModel: tenant.identity.businessModel, hasStrapi });

  const lines: string[] = [];
  lines.push(`# ${tenant.identity.name} — agent context`);
  lines.push("");
  lines.push("> Auto-generated by `@your-os/agent-context`. Do not edit by hand.");
  lines.push("> Edit `tenant.config.ts` instead and run `pnpm exec your-os sync`.");
  lines.push("");

  if (preface) {
    lines.push(preface);
    lines.push("");
  }

  lines.push("## Tenant identity");
  lines.push("");
  lines.push(`- Name: **${tenant.identity.name}**`);
  lines.push(`- Domain: **${tenant.identity.domain}**`);
  lines.push(`- Business model: **${tenant.identity.businessModel}**`);
  lines.push(`- Industry: ${tenant.identity.industry}`);
  lines.push(
    `- Conversion event: \`${tenant.conversion.eventName}\` (${tenant.conversion.primary})`,
  );
  lines.push(`- Content mode: ${hasStrapi ? "Strapi (or hybrid)" : "code"}`);
  lines.push("");

  if (tenant.audience.personas.length > 0) {
    lines.push("## Audience (personas)");
    lines.push("");
    for (const p of tenant.audience.personas) {
      lines.push(`- **${p.name}** — pain: ${p.pain}; value: ${p.value}`);
    }
    lines.push("");
  }
  if (tenant.audience.icps.length > 0) {
    lines.push("## Audience (ICPs)");
    lines.push("");
    for (const i of tenant.audience.icps) {
      lines.push(
        `- **${i.role}** (${i.industry ?? "n/a"} / ${i.companySize ?? "n/a"}) — committee: ${(i.buyingCommittee ?? []).join(", ") || "n/a"}; CEP: ${i.cep ?? "n/a"}`,
      );
    }
    lines.push("");
  }

  if (tenant.brand.distinctiveAssets.length > 0) {
    lines.push("## Brand DBAs (must hit ≥80% prevalence)");
    lines.push("");
    for (const d of tenant.brand.distinctiveAssets) {
      lines.push(`- **${d.value}** (${d.type}, target ${Math.round(d.prevalenceTarget * 100)}%)`);
    }
    lines.push("");
  }

  lines.push("## SEO posture");
  lines.push("");
  lines.push(`- Primary schema: \`${tenant.seo.primarySchemaType}\``);
  lines.push(`- Pillars: ${tenant.seo.pillars.map((p) => p.slug).join(", ")}`);
  lines.push("");

  if (tenant.agentContext.emphasize.length > 0) {
    lines.push("## Emphasize");
    lines.push("");
    for (const e of tenant.agentContext.emphasize) lines.push(`- ${e}`);
    lines.push("");
  }
  if (tenant.agentContext.forbid.length > 0) {
    lines.push("## Forbid");
    lines.push("");
    for (const f of tenant.agentContext.forbid) lines.push(`- ${f}`);
    lines.push("");
  }

  if (skills.length > 0) {
    lines.push("## Skills");
    lines.push("");
    lines.push(
      "These skills are loaded on-demand by your coding agent. Reference them by slug from the `@your-os/skills` catalog.",
    );
    lines.push("");
    const byFamily = new Map<string, typeof skills>();
    for (const s of skills) {
      const arr = byFamily.get(s.family) ?? [];
      arr.push(s);
      byFamily.set(s.family, arr);
    }
    for (const [family, arr] of byFamily) {
      lines.push(`### ${family}`);
      lines.push("");
      for (const s of arr) {
        lines.push(`- **${s.slug}** — ${s.description}`);
      }
      lines.push("");
    }
  }

  return `${lines.join("\n")}\n`;
}
