import type { ContentTypeDefinition, StrapiAttribute } from "@your-os/strapi-template";

export interface CodegenOptions {
  /** Module banner; defaults to a do-not-edit notice. */
  banner?: string;
  /** Tenant slug, used in the banner. */
  tenantSlug?: string;
}

const DEFAULT_BANNER = (tenantSlug?: string) =>
  `/**
 * AUTOGENERATED by @your-os/strapi-codegen.${tenantSlug ? ` tenant: ${tenantSlug}.` : ""}
 * Edits will be overwritten on next \`pnpm strapi:codegen\` run.
 */`;

const RESERVED = new Set(["default", "delete", "new", "interface"]);

function pascal(input: string): string {
  return input
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

function tsTypeForAttribute(attr: StrapiAttribute): string {
  switch (attr.type) {
    case "string":
    case "text":
    case "richtext":
    case "uid":
    case "datetime":
      return "string";
    case "integer":
    case "float":
      return "number";
    case "boolean":
      return "boolean";
    case "json":
      return "unknown";
    case "enumeration":
      return attr.enum.map((e) => JSON.stringify(e)).join(" | ");
    case "relation": {
      const target = attr.target.replace(/^api::/, "").split(".")[0] ?? "";
      const t = pascal(target);
      switch (attr.relation) {
        case "oneToMany":
        case "manyToMany":
          return `${t}[]`;
        default:
          return t;
      }
    }
    case "component":
      return attr.repeatable ? "unknown[]" : "unknown";
  }
}

function isOptional(attr: StrapiAttribute): boolean {
  if ("required" in attr && attr.required) return false;
  return true;
}

function renderInterface(def: ContentTypeDefinition): string {
  const name = pascal(def.info.singularName);
  const lines: string[] = [];
  lines.push(`export interface ${name} {`);
  lines.push("  id: number;");
  for (const [key, attr] of Object.entries(def.attributes)) {
    const safeKey = RESERVED.has(key) ? `"${key}"` : key;
    const opt = isOptional(attr) ? "?" : "";
    lines.push(`  ${safeKey}${opt}: ${tsTypeForAttribute(attr)};`);
  }
  if (def.options?.draftAndPublish) {
    lines.push("  publishedAt?: string | null;");
  }
  lines.push("  createdAt?: string;");
  lines.push("  updatedAt?: string;");
  lines.push("}");
  return lines.join("\n");
}

export function generateTypes(defs: ContentTypeDefinition[], opts: CodegenOptions = {}): string {
  const banner = opts.banner ?? DEFAULT_BANNER(opts.tenantSlug);
  const apiIdMap = defs
    .map((d) => `  ${pascal(d.info.singularName)}: "api::${d.apiId}.${d.apiId}";`)
    .join("\n");
  return [
    banner,
    "",
    ...defs.map(renderInterface),
    "",
    "export interface StrapiApiIdMap {",
    apiIdMap,
    "}",
    "",
    "export type StrapiContentType = keyof StrapiApiIdMap;",
    "",
  ].join("\n");
}
