import type { ContentTypeDefinition } from "@your-os/strapi-template";
import { describe, expect, it } from "vitest";
import { codegenFromContentTypes } from "./from-template.js";
import { generateTypes } from "./generator.js";

describe("generateTypes", () => {
  it("emits a typed interface per content-type with id and audit fields", () => {
    const out = codegenFromContentTypes({ tenantSlug: "test" });
    expect(out).toContain("export interface Article {");
    expect(out).toContain("id: number;");
    expect(out).toContain("publishedAt?: string | null;");
    expect(out).toContain("createdAt?: string;");
    expect(out).toContain("updatedAt?: string;");
    expect(out).toContain("AUTOGENERATED");
    expect(out).toContain("tenant: test");
  });

  it("relations resolve to PascalCase target names", () => {
    const out = codegenFromContentTypes();
    expect(out).toMatch(/pillar\?: Pillar;/);
    expect(out).toMatch(/personas\?: Persona\[\];/);
  });

  it("enumerations become string-literal unions", () => {
    const out = codegenFromContentTypes();
    expect(out).toContain(
      'intent?: "informational" | "transactional" | "commercial" | "navigational";',
    );
  });

  it("required fields drop the optional `?`", () => {
    const fixture: ContentTypeDefinition[] = [
      {
        apiId: "thing",
        info: { singularName: "thing", pluralName: "things", displayName: "Thing" },
        attributes: {
          name: { type: "string", required: true },
          note: { type: "text" },
        },
      },
    ];
    const out = generateTypes(fixture);
    expect(out).toMatch(/name: string;/);
    expect(out).toMatch(/note\?: string;/);
  });

  it("emits an api-id map for runtime lookups", () => {
    const out = codegenFromContentTypes();
    expect(out).toContain("export interface StrapiApiIdMap {");
    expect(out).toContain('Article: "api::article.article";');
    expect(out).toContain('OpportunityBrief: "api::opportunity-brief.opportunity-brief";');
  });
});
