import { type ContentEntity, resolveContentSource } from "@your-os/content-source";
import { listSkills } from "@your-os/skills";
import { createBrandLintLifecycles } from "@your-os/strapi-brand-lint-hook";
import { codegenFromContentTypes } from "@your-os/strapi-codegen";
import { generateDeployFiles } from "@your-os/strapi-deploy";
import { SEO_COMPONENT, SEO_COMPONENT_PATH } from "@your-os/strapi-seo";
import { StrapiContentSource, buildEntryTag, createRevalidateHandler } from "@your-os/strapi-sync";
import { CONTENT_TYPES, MigrationRunner } from "@your-os/strapi-template";
import { parseTenantConfig } from "@your-os/tenant-config";
import { describe, expect, it } from "vitest";
import tenantConfig from "../tenant.config.js";

interface ArticleE extends ContentEntity {
  title: string;
}

describe("examples/minimal-strapi end-to-end OS integration", () => {
  it("tenant.config validates and is in strapi-mode", () => {
    const parsed = parseTenantConfig(tenantConfig);
    expect(parsed.identity.slug).toBe("minimal-strapi");
    expect(parsed.strapi).toBeDefined();
    expect(Object.values(parsed.contentSources).every((s) => s.mode !== "code")).toBe(true);
  });

  it("strapi-codegen produces a usable types module from the OS schema", () => {
    const code = codegenFromContentTypes({ tenantSlug: tenantConfig.identity.slug });
    expect(code).toContain("export interface Article {");
    expect(code).toContain("AUTOGENERATED");
  });

  it("strapi-template + migration-runner are byte-stable", () => {
    expect(CONTENT_TYPES.length).toBeGreaterThan(5);
    const runner = new MigrationRunner([], CONTENT_TYPES);
    const plan = runner.plan(null);
    expect(plan.willApply).toEqual([]);
    expect(runner.listContentTypes()).toBe(CONTENT_TYPES);
  });

  it("strapi-seo component matches the documented path", () => {
    expect(SEO_COMPONENT_PATH).toBe("shared/seo");
    expect((SEO_COMPONENT.attributes.metaTitle as { required: boolean }).required).toBe(true);
  });

  it("strapi-brand-lint-hook works without strapi globals", () => {
    const lc = createBrandLintLifecycles({
      tenantConfig: parseTenantConfig(tenantConfig),
      bodyFields: ["body"],
    });
    expect(() =>
      lc.beforePublish({
        action: "publish",
        model: { uid: "api::article.article" },
        params: { data: { body: "Real shifts, real pay near you." } },
      }),
    ).not.toThrow();
  });

  it("strapi-deploy renders provider files for the configured provider", () => {
    const files = generateDeployFiles("render", {
      tenantSlug: tenantConfig.identity.slug,
      hostname: `cms.${tenantConfig.identity.domain}`,
    });
    const paths = new Set(files.map((f) => f.path));
    expect(paths.has("Dockerfile")).toBe(true);
    expect(paths.has("render.yaml")).toBe(true);
    expect(paths.has(".env.example")).toBe(true);
    expect(paths.has("RUNBOOK.md")).toBe(true);
  });

  it("revalidate handler forms canonical tags using the tenant slug", () => {
    expect(buildEntryTag(tenantConfig.identity.slug, "api::article.article", "x")).toBe(
      "minimal-strapi:article:x",
    );
    const handler = createRevalidateHandler({
      tenantSlug: tenantConfig.identity.slug,
      webhookSecret: "shh",
      invalidate: () => undefined,
    });
    expect(handler).toBeTypeOf("function");
  });

  it("StrapiContentSource resolves through the OS content-source seam", async () => {
    const fakeFetch: typeof globalThis.fetch = (async () =>
      new Response(JSON.stringify({ data: [{ slug: "hello", title: "Hello" }] }), {
        status: 200,
      })) as unknown as typeof globalThis.fetch;

    const source = await resolveContentSource<ArticleE>({
      spec: tenantConfig.contentSources.articles!,
      strapiSourceFactory: (collection) =>
        new StrapiContentSource<ArticleE>({
          baseUrl: tenantConfig.strapi!.baseUrl,
          collection,
          singularApiId: collection.replace(/s$/, ""),
          tenantSlug: tenantConfig.identity.slug,
          fetch: fakeFetch,
        }),
    });
    const out = await source.list();
    expect(out).toEqual([{ slug: "hello", title: "Hello" }]);
  });

  it("skills catalog surfaces strapi-tagged skills for this tenant", () => {
    const skills = listSkills({ hasStrapi: true });
    expect(skills.length).toBeGreaterThan(0);
  });
});
