import type { DiscoveryQuestion } from "./schema.js";

/**
 * Phase 3 Discovery questionnaire — minimal-viable set. Phase 4 adds branching
 * + AI Research suggestions. Order matters; the UI walks through top-to-bottom.
 */
export const discoveryQuestions: DiscoveryQuestion[] = [
  {
    id: "identity.name",
    path: "identity.name",
    kind: "text",
    prompt: "What is the public-facing name of this hub?",
    hint: "Shown in title tags + AGENTS.md.",
    required: true,
  },
  {
    id: "identity.slug",
    path: "identity.slug",
    kind: "text",
    prompt: "Choose a URL-safe slug (lowercase, dashes only).",
    hint: "Used as namespace for analytics, ISR cache tags, and the repo name.",
    required: true,
  },
  {
    id: "identity.domain",
    path: "identity.domain",
    kind: "url",
    prompt: "What domain will this hub live at?",
    hint: "Apex domain or full origin (we accept either).",
    required: true,
  },
  {
    id: "identity.industry",
    path: "identity.industry",
    kind: "text",
    prompt: "Industry or vertical, in 2-4 words.",
    hint: "Examples: 'shift work', 'B2B SaaS', 'home services'.",
    required: true,
  },
  {
    id: "identity.businessModel",
    path: "identity.businessModel",
    kind: "select",
    prompt: "Business model?",
    options: ["b2c", "b2b", "marketplace"],
    required: true,
  },
  {
    id: "audience.primaryPersona.name",
    path: "audience.primaryPersona.name",
    kind: "text",
    prompt: "Name of your primary audience persona.",
    hint: "Examples: 'shift worker', 'HR director', 'small-business owner'.",
    required: true,
  },
  {
    id: "audience.primaryPersona.pain",
    path: "audience.primaryPersona.pain",
    kind: "longtext",
    prompt: "What is their core pain in one sentence?",
    required: true,
  },
  {
    id: "audience.primaryPersona.value",
    path: "audience.primaryPersona.value",
    kind: "longtext",
    prompt: "What value do they get from this hub in one sentence?",
    required: true,
  },
  {
    id: "conversion.primary",
    path: "conversion.primary",
    kind: "select",
    prompt: "Primary conversion event?",
    options: ["app_install", "demo_booking", "sql", "newsletter", "purchase", "lead_form"],
    required: true,
  },
  {
    id: "conversion.ctaPattern",
    path: "conversion.ctaPattern",
    kind: "text",
    prompt: "Primary CTA template, with placeholders for tokens like {role}.",
    hint: "Examples: 'Find $15-$25/hr {role} Shifts', 'Book a 30-min demo'.",
    required: true,
  },
  {
    id: "brand.primaryDistinctiveAsset",
    path: "brand.primaryDistinctiveAsset",
    kind: "text",
    prompt: "Distinctive brand phrase or asset (Romaniuk DBA).",
    hint: "Repeated across content; brand-lint enforces ≥80% prevalence.",
    required: true,
  },
  {
    id: "brand.voiceTone",
    path: "brand.voiceTone",
    kind: "text",
    prompt: "Voice + tone in 2-6 words.",
    hint: "Examples: 'warm, plain-language', 'sharp, data-led, no fluff'.",
    required: true,
  },
  {
    id: "brand.readingLevel",
    path: "brand.readingLevel",
    kind: "select",
    prompt: "Target reading level?",
    options: ["6th_grade", "7th_grade", "8th_grade", "9th_grade", "10th_grade", "college"],
  },
  {
    id: "brand.pov",
    path: "brand.pov",
    kind: "select",
    prompt: "Point of view?",
    options: ["first_person", "second_person", "third_person"],
  },
  {
    id: "seo.primarySchemaType",
    path: "seo.primarySchemaType",
    kind: "text",
    prompt: "Primary schema.org type for content pages.",
    hint: "Examples: 'Article', 'JobPosting', 'HowTo', 'Product'.",
  },
  {
    id: "seo.pillars",
    path: "seo.pillars",
    kind: "longtext",
    prompt: "Top 3-7 content pillars, one per line, formatted: <slug> | <name> | <intent>",
    hint: "Intent ∈ informational|transactional|commercial|navigational. We parse and validate.",
    required: true,
  },
  {
    id: "contentStorage.mode",
    path: "contentStorage.mode",
    kind: "select",
    prompt: "Where will editorial content live?",
    options: ["code", "strapi"],
    hint: "Code-mode = TS files committed to the repo (best for technical teams). Strapi-mode = self-hosted Strapi 5 per tenant.",
    required: true,
  },
  {
    id: "contentStorage.strapi.baseUrl",
    path: "contentStorage.strapi.baseUrl",
    kind: "url",
    prompt: "Strapi base URL (only if Strapi-mode).",
    hint: "Example: https://cms.your-tenant.com",
  },
  {
    id: "contentStorage.strapi.deployProvider",
    path: "contentStorage.strapi.deployProvider",
    kind: "select",
    prompt: "Strapi deploy provider (only if Strapi-mode)?",
    options: ["render", "railway", "fly"],
  },
];
