import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { initTenant } from "@your-os/cli";
import { type DeployProvider, generateDeployFiles } from "@your-os/strapi-deploy";
import { CONTENT_TYPES } from "@your-os/strapi-template";
import type { Brief } from "./schema.js";
import { briefToTenantConfig } from "./translate.js";

export interface ScaffoldedFile {
  path: string;
  contents: string;
}

export interface ScaffoldOptions {
  /** Where to write the tenant repo. */
  outDir: string;
  /** Don't write to disk; return the file set. CI uses this for round-trip tests. */
  dryRun?: boolean;
}

export interface ScaffoldResult {
  files: ScaffoldedFile[];
}

/**
 * End-to-end scaffolder. Drives `@your-os/cli`'s `initTenant`, then layers
 * Strapi-track files when the brief is Strapi-mode.
 */
export async function scaffoldTenant(brief: Brief, opts: ScaffoldOptions): Promise<ScaffoldResult> {
  const tenant = briefToTenantConfig(brief);

  const init = await initTenant({ tenant, outDir: opts.outDir, dryRun: true });
  const files: ScaffoldedFile[] = [...init.files];

  if (brief.contentStorage.mode === "strapi") {
    const strapiOpts = brief.contentStorage.strapi!;
    const hostname = new URL(strapiOpts.baseUrl).host;
    const deployFiles = generateDeployFiles(strapiOpts.deployProvider as DeployProvider, {
      tenantSlug: brief.identity.slug,
      hostname,
      region: strapiOpts.region,
    });
    for (const f of deployFiles) {
      files.push({ path: `strapi/${f.path}`, contents: f.contents });
    }
    files.push({
      path: "strapi/schema/content-types.json",
      contents: `${JSON.stringify(CONTENT_TYPES, null, 2)}\n`,
    });
    files.push({
      path: "strapi/README.md",
      contents: renderStrapiReadme(brief),
    });
  }

  if (!opts.dryRun) {
    for (const file of files) {
      const target = join(opts.outDir, file.path);
      await mkdir(join(target, ".."), { recursive: true });
      await writeFile(target, file.contents, "utf8");
    }
  }
  return { files };
}

function renderStrapiReadme(brief: Brief): string {
  return `# Strapi for ${brief.identity.name}

> Generated by @your-os/configurator.

## Files

- \`Dockerfile\` — pinned Strapi 5 image.
- \`render.yaml\` / \`railway.json\` / \`fly.toml\` — provider config (you keep one).
- \`.env.example\` — required env vars per tenant; rotate secrets per tenant.
- \`schema/content-types.json\` — schema-as-code source. Apply via:
  \`pnpm exec your-os strapi:migrate --tenant ${brief.identity.slug}\`
- \`RUNBOOK.md\` — backups, restore, brand-lint hook, schema policy.

NEVER edit content-types via the Strapi admin in production.
`;
}
